#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_DIR="${ENV_DIR:-${ROOT_DIR}/env}"
RUNTIME_DIR="${ROOT_DIR}/.runtime"
RUNTIME_FILE="${RUNTIME_DIR}/secrets.env"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command '$1' is not installed." >&2
    exit 1
  fi
}

require_cmd curl
require_cmd jq

set -a
source "${ENV_DIR}/versions.env"
source "${ENV_DIR}/config.env"
if [[ -f "${ENV_DIR}/secrets.env" ]]; then
  source "${ENV_DIR}/secrets.env"
fi
set +a

VAULT_ADDR="${VAULT_ADDR:-http://${VAULT_PORT_BIND}:${VAULT_PORT}}"
VAULT_TOKEN="${VAULT_TOKEN:-${VAULT_DEV_ROOT_TOKEN:-}}"

if [[ -z "${VAULT_TOKEN}" ]]; then
  echo "ERROR: VAULT_TOKEN is not set and VAULT_DEV_ROOT_TOKEN is unavailable." >&2
  exit 1
fi

kv_read() {
  local path="$1"
  curl -fsS \
    -H "X-Vault-Token: ${VAULT_TOKEN}" \
    "${VAULT_ADDR}/v1/${VAULT_KV_MOUNT}/data/${VAULT_SECRET_PREFIX}/${path}"
}

kv_get() {
  local path="$1"
  local key="$2"
  local payload

  payload="$(kv_read "${path}")"
  jq -er --arg key "${key}" '.data.data[$key]' <<<"${payload}"
}

write_env_var() {
  local key="$1"
  local value="$2"
  local escaped
  escaped="${value//\'/\'\"\'\"\'}"
  printf "%s='%s'\n" "${key}" "${escaped}" >>"${RUNTIME_FILE}"
}

mkdir -p "${RUNTIME_DIR}"
umask 077
: >"${RUNTIME_FILE}"

{
  echo "# Generated by scripts/vault/render-secrets.sh"
  echo "# Source: ${VAULT_ADDR}/v1/${VAULT_KV_MOUNT}/data/${VAULT_SECRET_PREFIX}/*"
  echo
} >>"${RUNTIME_FILE}"

write_env_var "POSTGRES_USER" "$(kv_get postgres POSTGRES_USER)"
write_env_var "POSTGRES_PASSWORD" "$(kv_get postgres POSTGRES_PASSWORD)"
write_env_var "RUSTFS_ACCESS_KEY" "$(kv_get rustfs RUSTFS_ACCESS_KEY)"
write_env_var "RUSTFS_SECRET_KEY" "$(kv_get rustfs RUSTFS_SECRET_KEY)"
write_env_var "KEYCLOAK_ADMIN_USER" "$(kv_get keycloak KEYCLOAK_ADMIN_USER)"
write_env_var "KEYCLOAK_ADMIN_PASSWORD" "$(kv_get keycloak KEYCLOAK_ADMIN_PASSWORD)"
write_env_var "KEYCLOAK_DB_USER" "$(kv_get keycloak KEYCLOAK_DB_USER)"
write_env_var "KEYCLOAK_DB_PASSWORD" "$(kv_get keycloak KEYCLOAK_DB_PASSWORD)"
write_env_var "KEYCLOAK_GATEWAY_CLIENT_SECRET" "$(kv_get keycloak KEYCLOAK_GATEWAY_CLIENT_SECRET)"
write_env_var "OAUTH2_PROXY_CLIENT_SECRET" "$(kv_get oauth2-proxy OAUTH2_PROXY_CLIENT_SECRET)"
write_env_var "OAUTH2_PROXY_COOKIE_SECRET" "$(kv_get oauth2-proxy OAUTH2_PROXY_COOKIE_SECRET)"
write_env_var "VAULT_DEV_ROOT_TOKEN" "${VAULT_DEV_ROOT_TOKEN:-${VAULT_TOKEN}}"

echo "Wrote runtime secrets to ${RUNTIME_FILE}"
